language: haskell
ghc:
  - 7.6
  - 7.8

before_install:
  - sudo add-apt-repository ppa:chris-lea/zeromq -y
  - sudo apt-get update
  - sudo apt-get install libzmq3 libzmq3-dev git
  - cabal update

install:
  - cabal install --reorder-goals --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --reorder-goals --enable-tests --enable-benchmarks
  - cabal build
  - cabal test
  - cabal bench
