language: haskell
ghc:
  - 7.6
# - 7.4

before_install:
    - sudo add-apt-repository ppa:chris-lea/zeromq -y
    - sudo apt-get update
    - sudo apt-get install libzmq3 libzmq3-dev git
    - cabal update
    - cabal install cabal-install
    - export PATH=~/.cabal/bin:$PATH

install:
    - cabal sandbox init
    - cabal install --dependencies-only --enable-tests --enable-benchmarks --allow-newer=mtl,ansi-terminal,network-transport,base

script:
    - cabal configure --enable-tests --enable-benchmarks && cabal build && cabal test && cabal bench
